ConsoleApp3/WebApplicationTwitch/Models/Abonne.cs
namespace WebApplicationTwitch.Models
{
    /// <summary>
    /// Classe Abonne qui représente un abonné de Twitch 
    /// </summary>
    public class Abonne
    {
        public int Id { get; set; }
        public string Surnom { get; set; }
        public string ImageProfil { get; set; }
        public bool EstConnecte { get; set; }
        public int NombreDeConnexions { get; set; }
        /// <summary>
        /// Constructeur par défaut de la classe Abonne 
        /// </summary>
        public Abonne()
        {
        }
        /// <summary>
        /// Constructeur de la classe Abonne avec paramètres 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="surnom"></param>
        /// <param name="imageProfil"></param>
        /// <param name="estConnecte"></param>
        public Abonne(int id, string surnom, string imageProfil, bool estConnecte)
        {
            Id = id;
            Surnom = surnom;
            ImageProfil = imageProfil;
            EstConnecte = estConnecte;
        }
    }
}

ConsoleApp3/WebApplicationTwitch/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace WebApplicationTwitch.Models
{
    /// <summary>
    /// DbContext est une classe fournie par Entity Framework Core.
    /// </summary>
    public class DefaultDbContext : DbContext 
    {
        
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }

        /// <summary>
        /// Ici on définit une liste d'Abonnes qui sera connectée à une table en bdd (Abonnes)
        /// </summary>
        public DbSet<Abonne> Abonnes { get; set; }
        /// <summary>
        /// Ici on définit une liste de Gamers qui sera connectée à une table en bdd (Gamers)
        /// </summary>
        public DbSet<Gamer> Gamers { get; set; }
    }
}

ConsoleApp3/WebApplicationTwitch/Models/ErrorViewModel.cs
namespace WebApplicationTwitch.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConsoleApp3/WebApplicationTwitch/Models/Gamer.cs
namespace WebApplicationTwitch.Models
{
    /// <summary>
    /// Classe Gamer qui représente un gamer de Twitch
    /// </summary>
    public class Gamer
    {
        public int Id { get; set; }
        public int NombreTotalDeStreams { get; set; }
        /// <summary>
        ///  Constructeur de la classe Gamer. Il permet de créer un objet Gamer sans paramètres 
        /// </summary>
        public Gamer()
        {
        }
        /// <summary>
        ///  Constructeur de la classe Gamer avec paramètres 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="nombreTotalDeStreams"></param>
        public Gamer(int id, int nombreTotalDeStreams)
        {
            Id = id;
            NombreTotalDeStreams = nombreTotalDeStreams;
        }
    }
}

ConsoleApp3/WebApplicationTwitch/Controllers/AbonneController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationTwitch.Models;

namespace WebApplicationTwitch.Controllers
{
    /// <summary>
    ///  AbonneController est une classe qui hérite de la classe Controller fournie par ASP.NET Core MVC 
    /// </summary>
    public class AbonneController : Controller
    {
        /// <summary>
        /// context est une propriété privée de type DefaultDbContext qui va nous permettre de récupérer les données en bdd 
        /// </summary>
        private readonly DefaultDbContext context;

        /// <summary>
        /// Comme j'ai ajouté la ligne builder.Services.AddDbContext<DefaultDbContext>() dans le programme, alors ici on va récupérer une instance de DefaultDbContext déjà configurée et prête à l'emploi. 
        /// </summary>
        /// <param name="context"></param>
        public AbonneController(DefaultDbContext context)
        {
            this.context = context;
        }
        /// <summary>
        ///  On récupère la liste des abonnés et on les envoie à la vue List.cshtml
        /// </summary>
        /// <param name="filtre"></param>
        /// <returns></returns>
        public IActionResult List(string filtre)
        {           
            // Ici on récupère le premier gamer de la bdd
            Gamer gamer = context.Gamers.First(); 

            // On calcule le seuil de présence à partir du nombre total de streams et du pourcentage de présence (70%). Ce seuil va ainsi nous permettre de déterminer si un abonné est présent dans au moins 70% des streams ou non.
            double seuilPresence = gamer.NombreTotalDeStreams * 0.7;
            
            // On récupère la liste des abonnés
            var query = from item in context.Abonnes
                        select item;
            
            // filtre est la valeur de l'attribut value de l'option sélectionnée dans la liste déroulante du formulaire de la vue List.cshtml 
            if (filtre == "connectes")
            {
                // On filtre la liste des abonnés pour ne garder que ceux qui sont connectés 
                query = from item in query
                        where item.EstConnecte
                        select item;
            }
            else if (filtre == "presents")
            {
                // On filtre la liste des abonnés pour ne garder que ceux qui sont présents dans au moins 70% des streams
                query = from item in query
                        where item.NombreDeConnexions >= seuilPresence
                        select item;
            }

            string title;
            // Ici on va définir le titre <h2> de la page en fonction de la valeur de l'attribut value de l'option sélectionnée dans la liste déroulante du formulaire de la vue List.cshtml 
            switch (filtre)
            {
                case "connectes":
                    title = "Liste des abonnés connectés";
                    break;
                case "presents":
                    title = "Liste des abonnés les plus présents";
                    break;
                default:
                    title = "Liste de tous les abonnés";
                    break;
            }
            ViewData["Title"] = title;


            // On retourne la vue List.cshtml avec la liste des abonnés filtrée en paramètre
            return View("List", query.ToList());

        }
    }
}

ConsoleApp3/WebApplicationTwitch/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationTwitch.Models;

namespace WebApplicationTwitch.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsoleApp3/WebApplicationTwitch/Views/Abonne/List.cshtml
@model List<Abonne>;

<div class="text-center mb-5">
    <h1 class="display-4">Liste des abonnés</h1>
</div>

<div class="container mb-4">
    <form asp-controller="Abonne" asp-action="List" method="get">
        <div class="form-group mb-3">
            <label for="filtre">Filtrer :</label>
            <select id="filtre" name="filtre">
                <option value="tous">Tous les abonnés</option>
                <option value="connectes">Abonnés connectés</option>
                <option value="presents">Abonnés présents dans plus de 70% des streams</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Appliquer le filtre</button>
    </form>
</div>

<div class="container">
    <!-- Ici on affiche le titre <h2> de la page en fonction du filtre sélectionné -->
    <h2 class="mb-4">@ViewData["Title"]</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Surnom</th>
                <th>Image de profil</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Surnom</td>
                    <td><img src="/images/@item.ImageProfil" alt="Image de profil" /></td>
                </tr>
            }
        </tbody>
    </table>
</div>

ConsoleApp3/WebApplicationTwitch/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center mb-5">
    <h1 class="display-4">Bienvenue gamer !</h1>
</div>

<a class="btn btn-primary" asp-controller="Abonne" asp-action="List">Liste des abonnés</a>

ConsoleApp3/WebApplicationTwitch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationTwitch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationTwitch.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationTwitch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Abonne" asp-action="List">Liste des abonnés</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Politique de confidentialité</a>
                        </li>   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationTwitch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>