ConsoleApp3/SImulationTwitch/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace SImulationTwitch.Models
{
    /// <summary>
    /// DbContext est une classe fournie par Entity Framework Core.
    /// </summary>
    public class DefaultDbContext : DbContext 
    {
        
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }

        /// <summary>
        ///  C'est une liste ! Et elle sera connectée à une table en bdd
        /// </summary>
        public DbSet<Stream> Streams { get; set; }
    }
}

ConsoleApp3/SImulationTwitch/Models/ErrorViewModel.cs
namespace SImulationTwitch.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConsoleApp3/SImulationTwitch/Models/Stream.cs
namespace SImulationTwitch.Models
{
    public class Stream
    {       
        public int Id { get; set; }
        public string Titre { get; set; }
        public DateTime Date { get; set; }
        public string Status
        {
            get
            {
                var now = DateTime.Now;
                // Si la date du stream est supérieur à la date actuelle alors le stream est à venir
                if (Date > now)
                {
                    return "A venir";
                }
                // Si la date du stream est inférieur à la date actuelle et que la date du stream + 1 heure est supérieur à la date actuelle alors le stream est en cours. On définit donc qu'un stream dure 1 heure maximum pour simplifier le code.
                else if (Date <= now && Date.AddHours(1) >= now)
                { 
                    return "En cours";
                }
                // Sinon le stream est fini
                else
                {
                    return "Fini";
                }
            }
        }
    }
}

ConsoleApp3/SImulationTwitch/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SImulationTwitch.Models;
using System.Diagnostics;

namespace SImulationTwitch.Controllers
{
    /// <summary>
    ///  Le controller Home est le controller par défaut de l'application (il est appelé quand on lance l'application)
    /// </summary>
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DefaultDbContext context;
        
        public HomeController(ILogger<HomeController> logger, DefaultDbContext context)
        {
            _logger = logger;
            this.context = context;
        }
        /// <summary>
        ///  On récupère la liste des streams et on les envoie à la vue Index.cshtml
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {           
            // ToList permet de transformer un IEnumerable en List (ou autre collection) 
            var streams = this.context.Streams.ToList();
            return View(streams);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsoleApp3/SImulationTwitch/Controllers/StreamController.cs
using Microsoft.AspNetCore.Mvc;
using SImulationTwitch.Models;
// Ici on importe la classe Stream qui se trouve dans le namespace SImulationTwitch.Models
using Stream = SImulationTwitch.Models.Stream;

namespace SImulationTwitch.Controllers
{
    /// <summary>
    /// Le controller Stream est le controller qui gère les streams
    /// </summary>
    public class StreamController : Controller
    {
        private readonly DefaultDbContext context;
        /// <summary>
        /// On injecte le contexte de données dans le controller pour pouvoir utiliser les données de la base de données
        /// </summary>
        /// <param name="context"></param>
        public StreamController(DefaultDbContext context)
        {
            this.context = context;
        }

        public IActionResult Add()
        {
            return View();
        }     

        [HttpPost]
        public IActionResult Add(Stream stream)
        {
            // On ajoute le stream à la liste des streams
            this.context.Streams.Add(stream); 
            // On sauvegarde les changements dans la base de données
            this.context.SaveChanges();
            
            return RedirectToAction("Index", "Home");
        }
    }
}

ConsoleApp3/SImulationTwitch/Views/Home/Index.cshtml
@{ 
    ViewData["Title"] = "Home Page";
}

<div class="text-center mb-5">
    <h1 class="display-4">Bienvenue gamer !</h1>
</div>


<div class="container">
    <h2 class="mb-4">Liste des streams</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Date et heure</th>
                <th>Titre</th>
                <th>Statut</th>
            </tr>
        </thead>
        <tbody>
            <!-- Pour chaque stream dans la liste, on affiche les informations -->
            @foreach (var stream in Model)
            {
                <tr>
                    <!-- On utilise la méthode ToString() pour formater la date --> 
                    <td>@stream.Date.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@stream.Titre</td>
                    <td>@stream.Status</td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn btn-primary" asp-controller="Stream" asp-action="Add">Nouveau Stream</a>
</div>

ConsoleApp3/SImulationTwitch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SImulationTwitch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SImulationTwitch.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SImulationTwitch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stream" asp-action="Add">Nouveau stream</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Politique de confidentialité</a>
                        </li>                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SImulationTwitch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ConsoleApp3/SImulationTwitch/Views/Stream/Add.cshtml
<div class="text-center mb-5">
    <h1 class="display-4">Création de Streams</h1>
</div>
<div class="container mb-4">
    <form asp-controller="Stream" asp-action="Add" method="post">
        <div class="form-group">
            <label for="Titre">Titre :</label>
            <input id="Titre" name="Titre" class="form-control" required />
        </div>
        <div class="form-group mb-3">
            <label for="Date">Date et heure :</label>
            <input type="datetime-local" id="Date" name="Date" class="form-control" required />
        </div>
        <button type="submit" class="btn btn-primary">Créer un stream</button>
    </form>
</div>